/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.lfa.academy.view;

/**
 *
 * @author charm_000
 */
public class MainPageView extends javax.swing.JFrame {

    /**
     * Creates new form MainPageView
     */
    public MainPageView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        displayStudentTab = new javax.swing.JMenu();
        addStudentTab = new javax.swing.JMenuItem();
        dispStudentTab = new javax.swing.JMenuItem();
        searchStudentTab = new javax.swing.JMenuItem();
        deleteStudentTab = new javax.swing.JMenuItem();
        updateStudentTab = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenu5.setText("jMenu5");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Menu");

        displayStudentTab.setText("Student");

        addStudentTab.setText("Add Student");
        addStudentTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentTabActionPerformed(evt);
            }
        });
        displayStudentTab.add(addStudentTab);

        dispStudentTab.setText("Display Student List");
        dispStudentTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispStudentTabActionPerformed(evt);
            }
        });
        displayStudentTab.add(dispStudentTab);

        searchStudentTab.setText("Search Student ");
        searchStudentTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentTabActionPerformed(evt);
            }
        });
        displayStudentTab.add(searchStudentTab);

        deleteStudentTab.setText("Delete Student");
        deleteStudentTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentTabActionPerformed(evt);
            }
        });
        displayStudentTab.add(deleteStudentTab);

        updateStudentTab.setText("Update Student Information");
        updateStudentTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentTabActionPerformed(evt);
            }
        });
        displayStudentTab.add(updateStudentTab);

        jMenu1.add(displayStudentTab);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Course");
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Exit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentTabActionPerformed
         new AddStudent().setVisible(true);
    }//GEN-LAST:event_addStudentTabActionPerformed

    private void searchStudentTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentTabActionPerformed
        new SearchStudentView().setVisible(true);
    }//GEN-LAST:event_searchStudentTabActionPerformed

    private void dispStudentTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispStudentTabActionPerformed
        new DisplayStudentView().setVisible(true);
    }//GEN-LAST:event_dispStudentTabActionPerformed

    private void deleteStudentTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentTabActionPerformed
        new DeleteStudentView().setVisible(true);
    }//GEN-LAST:event_deleteStudentTabActionPerformed

    private void updateStudentTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentTabActionPerformed
      new UpdateStudentView().setVisible(true);
    }//GEN-LAST:event_updateStudentTabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPageView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addStudentTab;
    private javax.swing.JMenuItem deleteStudentTab;
    private javax.swing.JMenuItem dispStudentTab;
    private javax.swing.JMenu displayStudentTab;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem searchStudentTab;
    private javax.swing.JMenuItem updateStudentTab;
    // End of variables declaration//GEN-END:variables
}
